#include <string.h>

#define MOD_RT_UTILS		1

#define FUN_GRAMSCHMIDT			101
#define FUN_CALCDOTPRODUCT		102
#define FUN_CALCCELLCENTRES		103
#define FUN_GETNEXTEDGESET		104
#define FUN_GRIDPOINTSARENEIGHBOURS	105
#define FUN_EDGESFORMACELL		106
#define FUN_CELLVERTICESMATCH		107
#define FUN_ADDRAWCELL			108
#define FUN_GETCELLSFROMGRID		109
#define FUN_GETEDGES			110
#define FUN_CALCBARYCOORDS		111

#define MOD_RAYTHRUCELLS	2

#define FUN_EXTRACTFACE			201
#define FUN_GETNEWENTRYFACEI		202
#define FUN_CALCFACEINNMINUS1		203
#define FUN_INTERSECTLINEWITHFACE	204
#define FUN_FOLLOWGOODCHAIN		205
#define FUN_BUILDRAYCELLCHAIN		206
#define FUN_FOLLOWRAYTHROUGHCELLS	207

#define MOD_MESHTOCUBE		3

#define FUN_INTERPOLATEATFACE		301
#define FUN_GETFACEINTERPSALONGRAY	302
#define FUN_INTERPONGRIDALONGRAY	303
#define FUN_GENERATEVOXELINDEX		304
#define FUN_GENERATENEXTPIXELCOMBO	305
#define FUN_CELLSTOHYPERCUBE		306

#define MOD_SECOND_ORDER	4

#define FUN_EVALUATE2NDORDERSHAPEFNS		401
#define FUN_INTERPOLATE2NDORDERCELL		402
#define FUN_GETPARABOLICSHAPEFNS		403
#define FUN_INTERPOLATEPARABOLIC		404
#define FUN_FACEBARYTOCELLBARY			405
#define FUN_FILLBARYBUFFVALUES			406
#define FUN_GETINTERPSALONGRAY			407
#define FUN_SETRASTERFLAGS			408
#define FUN_INTERPONGRIDALONGRAY2NDORDER	409


#ifndef TRUE
#define TRUE                   (_Bool)1
#endif

#ifndef FALSE
#define FALSE                  (_Bool)0
#endif



_Bool	getModuleI(char *moduleName, int *moduleI);
_Bool	getFunctionI(char *moduleName, int moduleI, int *functionI);
